version: 1
issues: True
labels:
  - label: WIP
    branch: "wip"
  - label: WIP
    title: "^WIP:.*"
  - label: WOP
    title: "^WOP:.*"
  - label: S
    size-below: 10
  - label: M
    size-above: 9
    size-below: 100
  - label: L
    size-above: 100
  - label: "TestFileMatch"
    files: 
    - "cmd/.*.go"
    - "pkg/.*.go"
  - label: "Test"
    authors: 
      - "Test1"
      - "Test2"
